version: "3"
networks:
  calculator:
services:
  nginx:
    image: nginx:stable-alpine
    container_name: calculator_nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      calculator:
  redis:
    image: redis:4.0
    container_name: calculator_redis
    ports:
      - "6382:6379"
    networks:
      - calculator
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: calculator_app
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - calculator
